=== Urigo/accounter-fullstack/packages/modern-poalim-scraper/src/schemas/foreignSwiftTransactions.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "metadata": {
      "type": "object",
      "properties": {
        "messages": {
          "type": "array",
          "items": {
            "type": "object",
            "oneOf": [
              {
                "properties": {
                  "messageDescription": {
                    "type": "string"
                  },
                  "messageCode": {
                    "type": "number"
                  },
                  "severity": {
                    "type": "string"
                  },
                  "messagePurposeCategoryCode": {
                    "type": "string"
                  }
                },
                "required": [
                  "messageDescription",
                  "messageCode",
                  "severity",
                  "messagePurposeCategoryCode"
                ]
              },
              {
                "properties": {
                  "messageDescription": {
                    "type": "string",
                    "enum": ["לתשומת לבך: לא נמצאו זיכויי סוויפט בטווח התאריכים המוצג."]
                  },
                  "messageCode": {
                    "type": "number"
                  },
                  "severity": {
                    "type": "string"
                  }
                },
                "required": ["messageDescription", "messageCode", "severity"]
              }
            ]
          }
        },
        "links": {
          "type": "object",
          "properties": {},
          "required": []
        }
      },
      "required": ["messages", "links"]
    },
    "trailersCounter": {
      "type": "number"
    },
    "minInputDate": {
      "type": "number"
    },
    "formattedMinInputDate": {
      "type": ["string", "null"]
    },
    "swiftsList": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "startDate": {
            "type": "number"
          },
          "formattedStartDate": {
            "type": "string"
          },
          "swiftStatusCode": {
            "type": "string"
          },
          "swiftStatusDesc": {
            "type": "string"
          },
          "amount": {
            "type": "number"
          },
          "currencyCodeCatenatedKey": {
            "type": "string"
          },
          "currencyLongDescription": {
            "type": "string"
          },
          "chargePartyName": {
            "type": "string"
          },
          "referenceNumber": {
            "type": "string"
          },
          "transferCatenatedId": {
            "type": "string"
          },
          "dataOriginCode": {
            "type": "number"
          }
        },
        "required": [
          "startDate",
          "formattedStartDate",
          "swiftStatusCode",
          "swiftStatusDesc",
          "amount",
          "currencyCodeCatenatedKey",
          "currencyLongDescription",
          "chargePartyName",
          "referenceNumber",
          "transferCatenatedId",
          "dataOriginCode"
        ]
      }
    },
    "fyiMessages": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "messageCode": {
            "type": "number"
          },
          "messageTypeCode": {
            "type": "string"
          },
          "screenCommentText": {
            "type": "string"
          }
        },
        "required": ["messageCode", "messageTypeCode", "screenCommentText"]
      }
    },
    "currencyCodeCatenatedKey": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "values": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "systemCode": {
                "type": "number"
              },
              "bankNumber": {
                "type": "number"
              },
              "currencyCode": {
                "type": "number"
              },
              "currencyShortedDescription": {
                "type": "string"
              },
              "currencySwiftCode": {
                "type": "string"
              },
              "currencyLongDescription": {
                "type": "string"
              },
              "compKey": {
                "type": "string"
              },
              "currencyUnitsQuantity": {
                "type": "number"
              }
            },
            "required": [
              "systemCode",
              "bankNumber",
              "currencyCode",
              "currencyShortedDescription",
              "currencySwiftCode",
              "currencyLongDescription",
              "compKey",
              "currencyUnitsQuantity"
            ]
          }
        }
      },
      "required": ["code", "values"]
    },
    "swiftStatusCode": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "values": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "swiftStatusCode": {
                "type": "string"
              },
              "swiftStatusDesc": {
                "type": "string"
              }
            },
            "required": ["swiftStatusCode", "swiftStatusDesc"]
          }
        }
      },
      "required": ["code", "values"]
    }
  },
  "required": [
    "metadata",
    "trailersCounter",
    "minInputDate",
    "formattedMinInputDate",
    "swiftsList",
    "fyiMessages",
    "currencyCodeCatenatedKey",
    "swiftStatusCode"
  ]
}

=== Urigo/accounter-fullstack/old-accounter/src/transfers.json
{
  "metadata": {
    "messages": [
      {
        "messageDescription": "זיכויי הסוויפט המופיעים במסך זה הם על תנאי ולידיעה בלבד , עד לזיכוי חשבונך בפועל",
        "messageCode": 55,
        "severity": "I",
        "messagePurposeCategoryCode": "1"
      }
    ],
    "links": {}
  },
  "trailersCounter": 50,
  "minInputDate": 20210127,
  "formattedMinInputDate": "2021-01-27T00:00:00.000Z",
  "swiftsList": [
    {
      "startDate": 20210210,
      "formattedStartDate": "2021-02-10T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 1512.56,
      "currencyCodeCatenatedKey": "320;012;100;",
      "currencyLongDescription": "אירו",
      "chargePartyName": "STICHTING FRONTEND AMSTERDAM",
      "referenceNumber": "GER004561041",
      "transferCatenatedId": "91286710.02.2021MT103BARCDEFFXXXGER004561041    89525000000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210405,
      "formattedStartDate": "2021-04-05T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "095305456",
      "transferCatenatedId": "91286705.04.2021MT103MRMDUS33XXX095305456       73421600000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210514,
      "formattedStartDate": "2021-05-14T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 50000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "133527977",
      "transferCatenatedId": "91286714.05.2021MT103MRMDUS33XXX133527977       33873000000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210525,
      "formattedStartDate": "2021-05-25T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "144584924",
      "transferCatenatedId": "91286725.05.2021MT103MRMDUS33XXX144584924       46792000000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210530,
      "formattedStartDate": "2021-05-30T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "148661477",
      "transferCatenatedId": "91286730.05.2021MT103MRMDUS33XXX148661477       55216800000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210620,
      "formattedStartDate": "2021-06-20T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "169577940",
      "transferCatenatedId": "91286720.06.2021MT103MRMDUS33XXX169577940       87120800000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210629,
      "formattedStartDate": "2021-06-29T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "179674777",
      "transferCatenatedId": "91286729.06.2021MT103MRMDUS33XXX179674777       00410200000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210725,
      "formattedStartDate": "2021-07-25T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "204558734",
      "transferCatenatedId": "91286725.07.2021MT103MRMDUS33XXX204558734       43061700000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210801,
      "formattedStartDate": "2021-08-01T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "211634732",
      "transferCatenatedId": "91286701.08.2021MT103MRMDUS33XXX211634732       53861100000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210824,
      "formattedStartDate": "2021-08-24T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "235556603",
      "transferCatenatedId": "91286724.08.2021MT103MRMDUS33XXX235556603       86889300000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210901,
      "formattedStartDate": "2021-09-01T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "243612520",
      "transferCatenatedId": "91286701.09.2021MT103MRMDUS33XXX243612520       99322100000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210919,
      "formattedStartDate": "2021-09-19T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 9972.5,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "OUTREACH CORPORATION",
      "referenceNumber": "S0612602807E01",
      "transferCatenatedId": "91286719.09.2021MT103CITIUS33XXXS0612602807E01  23800000000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20210926,
      "formattedStartDate": "2021-09-26T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "267597611",
      "transferCatenatedId": "91286726.09.2021MT103MRMDUS33XXX267597611       32553400000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20211010,
      "formattedStartDate": "2021-10-10T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "281587882",
      "transferCatenatedId": "91286710.10.2021MT103MRMDUS33XXX281587882       53966600000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20211012,
      "formattedStartDate": "2021-10-12T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 49972.5,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "LANCE GLOBAL, INC.",
      "referenceNumber": "S0612855A0D701",
      "transferCatenatedId": "91286712.10.2021MT103CITIUS33XXXS0612855A0D701  57365000000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20211015,
      "formattedStartDate": "2021-10-15T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 49972.5,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "OUTREACH CORPORATION",
      "referenceNumber": "S06128819F6D01",
      "transferCatenatedId": "91286715.10.2021MT103CITIUS33XXXS06128819F6D01  63869500000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20211024,
      "formattedStartDate": "2021-10-24T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "295579777",
      "transferCatenatedId": "91286724.10.2021MT103MRMDUS33XXX295579777       75316700000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20211102,
      "formattedStartDate": "2021-11-02T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 25000.0,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "DALET DIGITAL MEDIA SYSTEMS USA INC",
      "referenceNumber": "305594431",
      "transferCatenatedId": "91286702.11.2021MT103MRMDUS33XXX305594431       89280300000000",
      "dataOriginCode": 2
    },
    {
      "startDate": 20211114,
      "formattedStartDate": "2021-11-14T00:00:00.000Z",
      "swiftStatusCode": "0Y",
      "swiftStatusDesc": "ההעברה בוצעה",
      "amount": 24972.5,
      "currencyCodeCatenatedKey": "320;012;019;",
      "currencyLongDescription": "דולר ארה\"ב",
      "chargePartyName": "LANCE GLOBAL, INC.",
